name: manage-azure-policy-68cd3baf
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'initiatives/Inherit_parent_tag_from_resource_group_18f69971-74da-4bae-9109-a04a8a88d0a6/**'
#      - 'initiatives/Inherit_parent_tag_from_resource_group_5f1a4d9f52a54a0f99bfe2bc/**'
#      - .github/workflows/manage-azure-policy-68cd3baf.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_68cd3baf}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          initiatives/Inherit_parent_tag_from_resource_group_18f69971-74da-4bae-9109-a04a8a88d0a6/**
          initiatives/Inherit_parent_tag_from_resource_group_5f1a4d9f52a54a0f99bfe2bc/**
